// <auto-generated />
namespace Presentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class REMOVED_FINISHDATE_TO_DESTINATION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REMOVED_FINISHDATE_TO_DESTINATION));
        
        string IMigrationMetadata.Id
        {
            get { return "201705281123412_REMOVED_FINISHDATE_TO_DESTINATION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
