// <auto-generated />
namespace Presentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ADDED_BIRTHDAY_AND_CPF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDED_BIRTHDAY_AND_CPF));
        
        string IMigrationMetadata.Id
        {
            get { return "201705211901199_ADDED_BIRTHDAY_AND_CPF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
