// <auto-generated />
namespace Presentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CHANGES_IN_TRAVEL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CHANGES_IN_TRAVEL));
        
        string IMigrationMetadata.Id
        {
            get { return "201706112224322_CHANGES_IN_TRAVEL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
